name: Test and Build

on:
  push:
    branches-ignore:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Test Code
        if: ${{ success() }}
        run: npm run test
      - name: Build Code
        if: ${{ success() }}
        run: npm run build
