name: Test, Build and Publish to S3

on:
  push:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Test Code
        if: ${{ success() }}
        run: npm run test
      - name: Build Code
        if: ${{ success() }}
        run: npm run build
      - name: Deploy to S3
        if: ${{ success() }}
        uses: reggionick/s3-deploy@v3
        with:
          bucket: ${{ secrets.AWS_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          folder: 'dist'
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          delete-removed: true
